### ISSUE TITLE
Flicking Titles

### ISSUE THREAD

**Issue by kelalaka153** [androidseb/android-google-maps-floating-marker-titles#3] opened 2019-02-22 12:51 UTC
When the markers are too close, there is a flicking between titles of markers. One title just appears in grey then disappears, in the mean time the other one turn into grey and disappears. This goes on as long you can resolve it by zooming in or out. 

Is there a solution for this?

Note : this happens when all has the same z level.

**Comment by androidseb** [comment] 2019-02-23 16:18
Hey, thank you for reporting this.
I haven't been able to reproduce the issue.
Have you been able to reproduce this with the unmodified sample app?
If you make modifications, what are they?

**Comment by kelalaka153** [comment] 2019-02-24 15:05
I think I've found the reason. From a  previous  [feature ](https://github.com/androidseb/android-google-maps-floating-marker-titles/issues/2) I asked about displaying the title on the right.  If I'm changing back to the original everything works fine. Maybe the dip value is not correct. I've changed the same lines from the original app and get a similar result.

**Comment by androidseb** [comment] 2019-02-24 18:58
Yeah, it seems that in that quick code change proposal, I overlooked consistency with the 
`GMFMTGeometryCache.computeDisplayAreaRect` method...
This solution I proposed was a hack and was not a fully fledged feature, so there might be other caveats. I won't be building new features for now, but if you want to add a "title placement" gravity feature, and can get it to fully work, I'll gladly review any pull request you send my way :-)

Closing this for now since this is a feature request and I'm not willing to invest time dealing with feature requests at the moment. I'll update the readme of the project to clarify this.

**Closed as completed by androidseb** 2019-02-24 18:58 UTC
